name: flutter_clean_architecture
description: Flutter Clean Architecture Series
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.0
  ionicons: ^0.2.2

  # Networking
  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.6

  # State Management
  flutter_bloc: ^8.1.2

  # Others
  flutter_hooks: ^0.18.5+1
  get_it: ^7.2.0
  floor: ^1.4.1
  equatable: ^2.0.5
  oktoast: ^3.3.1
  awesome_dio_interceptor: ^0.0.2+4
  auto_route: ^5.0.4
  flutter_svg: ^1.1.5
  material: ^1.0.0+2
  flutter_screenutil: ^5.7.0
  dotted_border: ^2.0.0+3
  dropdown_button2: ^2.1.3
  geolocator: ^9.0.2
  location: ^4.3.0
  geocoding: ^2.1.0
  lint: ^1.10.0
  package_info_plus: ^1.0.6
  flutter_background_service: ^2.4.6
  flutter_local_notifications: ^14.1.1
  #  photo view
  photo_view: ^0.14.0
  image_picker: ^0.8.7+1
  #searchable dropdown
  flutter_typeahead: ^4.6.2
  # convert date formate
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  auto_route_generator: ^5.0.3
  retrofit_generator: ^4.1.2
  floor_generator: ^1.4.1
  build_runner: ^2.3.3
  #  pin entry view
  #  pinput: ^2.2.31
  shared_preferences: ^2.0.12
  #  request logger
  dio_logging_interceptor: ^1.0.1
  cached_network_image: ^3.2.1
  permission_handler: ^10.2.0
  device_info_plus: ^4.1.2
  file_picker: ^5.2.0
  get: ^4.6.5
  get_it: ^7.2.0
  google_maps_flutter: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_Bold.ttf
        - asset: assets/fonts/Butler_Light.ttf
        - asset: assets/fonts/Butler_Regular.ttf

    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf

    - family: OpenSans_normal
      fonts:
        - asset: assets/fonts/OpenSans_normal.ttf

  assets:
    - assets/images/

